### ISSUE TITLE
Error in finding input video file

### ISSUE THREAD

**Issue by preksha12** [agermanidis/thingscoop#2]
Whenever I run thingscoop for any video input do I need to store that input file explicitly at some location,if yes what should be the location,currently I saved one video koyaanisqatsi.mp4 in thingscoop directory then after running 
thingscoop describe koyaanisqatsi.mp4 -m googlenet_places 
query in terminal I am getting following error:-
preksha@preksha:~/thingscoop$ thingscoop describe high.mp4 -m googlenet_places
Traceback (most recent call last):
  File "/usr/local/bin/thingscoop", line 52, in <module>
    sys.exit(thingscoop.main(args))
  File "/home/preksha/thingscoop/thingscoop/**init**.py", line 104, in main
    recreate_index=recreate_index
  File "/home/preksha/thingscoop/thingscoop/search.py", line 107, in label_videos
    recreate_index=recreate_index
  File "/home/preksha/thingscoop/thingscoop/search.py", line 80, in label_video
    temp_frame_dir, frames = extract_frames(filename, sample_rate=sample_rate)
  File "/home/preksha/thingscoop/thingscoop/utils.py", line 39, in extract_frames
    subprocess.check_output(["ffmpeg", "-i", filename, "-vf", "fps="+str(sample_rate), dest])
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, _popenargs, *_kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Kindly provide me guidance for solving this error.

**Comment by agermanidis** [comment]
You might be missing ffmpeg. Try `brew install ffmpeg` (Mac OS X) or `sudo apt-get install ffmpeg` (Ubuntu).

**Comment by preksha12** [comment]
I have installed ffmpeg and now it is showing following error

preksha@preksha:~/thingscoop$ thingscoop preview  koyaanisqatsi.mp4Traceback (most recent call last):
  File "/usr/local/bin/thingscoop", line 52, in <module>
    sys.exit(thingscoop.main(args))
  File "/home/preksha/thingscoop/thingscoop/**init**.py", line 95, in main
    preview(args['<file>'], classifier)
  File "/home/preksha/thingscoop/thingscoop/preview.py", line 41, in preview
    duration = int(get_video_duration(filename))
  File "/home/preksha/thingscoop/thingscoop/preview.py", line 20, in get_video_duration
    duration_string = re.findall(r'Duration: ([0-9:]*)', matches[0])[0]
IndexError: list index out of range

**Comment by preksha12** [comment]
I am not able to identify where the video is to be inputted in code.

**Comment by preksha12** [comment]
Thank you for help query is resolved now.
